### ISSUE TITLE
Divide by Zero in calc_error

### ISSUE THREAD

**Issue by teubert** [nasa/prog_models#504]
Identified by @aqitya 

PrognosticsModel.calc_error() throws a divide by zero exception when the model is configured in a way that is unstable (i.e., a state becomes NaN) in the first step (e.g., BatteryElectroChemEOD with a qMax of 4000). See https://github.com/nasa/prog_models/blob/f0891d59e4afd726f12812d273f6d97e7abc7a9f/src/prog_models/prognostics_model.py#L1176-L1178

This is of course undesired behavior. I see three options here:
1. if the model goes unstable at any point return NaN error (or Inf if NaN isn't treated correctly by estimate_params)
2. Of the model goes unstable before some cutoff (e.g., 90% of the points have passed), return NaN error. If it goes unstable at any other point, warn and return an estimate of error from the points to that point. 
3. Only if the model goes unstable at the first timestep, return NaN error. If it goes unstable at any other point, warn and return an estimate of error from the points to that point. 

We will want to make sure consider the following cases in our decision:
1. The case where this was first identified, the model is never stable so we get NaN on the first timestep, then we definitely want to return Nan (or Inf, see message above)
2. Case where we're running estimate_params and the model goes unstable midway through. Not sure what we want to do here
3. Case where we're running estimate_params and the model goes unstable at the very last timestep. This is frequently the case when training on run-to-failure data. In this case the parameters may be very close to the "correct" or best values. 
4. Case where we're running estimate_params and the model never goes unstable- this one we obviously want to work

We also should keep in mind that calc_error can be used outside of estimate_params

**Comment by aqitya** [comment]
Hmm, tough call. Right now I am leaning towards the second option but deciding what exactly the threshold should be.

Since the last timestep frequently goes unstable, we should definitely accommodate this case. 

However, if the model goes unstable at any given time before the last timestep (or maybe if it goes unstable at any point before 90% of the timesteps have been processed), I would probably stick to giving an error since the results would not be very useful at all. 

Regarding the last point, maybe a user is providing calc_error an unstable model specifically because it is easier to provide one than not. This is because it is easier to provide an unstable model than it is to correctly identify up to what point the model becomes unstable and fix it. Thus, we can provide a warning that not only states that the calc_error may not be accurate since it only accommodates up to a particular timestep, providing more information in case the user did not intend to pass in that particular model.

Let me know if there was anything in my reasoning that does not make much sense.

Finally, is there any way a timestep could fail but the timesteps following are not unstable?

**Comment by kjjarvis** [comment]
Great description of the issue, @teubert, I agree with everything you said. As @aqitya suggested, I lean towards your #2 solution, where past some threshold, if it becomes unstable, we still return an error value (without including this instability), but we warn the user that this is occurring. If instability occurs before this threshold, I tend to think we should return infinity, but here are some thoughts on this. 

In the case of using calc_error for parameter estimation, I agree that if the model goes unstable much earlier than about a 90% threshold, this is a problem. In terms of estimating parameters, it would make sense to return infinity for this error.

However, thinking about the fact that calc_error can be used in many other use-cases, completely unrelated to parameter estimation, I can see a scenario where a user might be interested in an error value for a specific portion of the simulation. For example, suppose a user had data from a full battery discharge, but was only curious about how our model would predict it for the first ~5 minutes for a quick flight. In this case, the user might not care that the error gets large half way through the full simulation. One idea would be to add a functionality to calc_error where the user can define the threshold for where stability matters. In the case of parameter estimation, we'd likely define it as 90%+. However, this does complicate things a bit, so perhaps it's easier that we define it at some fixed value and document it. Then, in the case described here, a user could cut the data before passing it to calc_error. 

Just a few thoughts. I'm happy with option #2.

**Comment by teubert** [comment]
After discussing this, we settled on option 2:

If the model goes unstable before some **configurable** cutoff (e.g., 95% of the points have passed), return NaN error. If it goes unstable at any other point, warn and return an estimate of error from the points to that point. By default the cutoff can be a high number (e.g., 95%), but users can set it to something else.
